# This workflow uses actions that are not certified by GitHub.
# They are provided by a third-party and are governed by
# separate terms of service, privacy policy, and support
# documentation.
name: D

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - uses: dlang-community/setup-dlang@v1.0.3

    - name: 'Build'
      run: |
        make frontend
        make backend
  test:
    name: Run unit tests
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v2
    - uses: dlang-community/setup-dlang@v1.0.3
    
    - name: 'Test'
      run: |
        dub test --compiler=$DC
