# This workflow uses actions that are not certified by GitHub.
# They are provided by a third-party and are governed by
# separate terms of service, privacy policy, and support
# documentation.
name: D

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    name: Test and Build
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
      
    - name: D Compiler Installation
      uses: dlang-community/setup-dlang@v1.0.3
      with:
        compiler: dmd-2.095

    - name: 'Backend Tests'
      run: dub test --compiler=$DC
      
    - name: 'Build backend'
      run: make backend
  
    - name: 'Build frontend'
      run: make frontend
